language: ruby
script: "script/test_all"
bundler_args: "--standalone --binstubs --without documentation"
notifications:
  webhooks:
    urls:
      - http://1c02f2d8.ngrok.com/projects/7536912f-1895-4b68-b5fa-3d139f3323ea/status
    on_start: true
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.2.0
  - ruby-head
  - ree
  - jruby-18mode
  - jruby
  - jruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx

